using Microsoft.EntityFrameworkCore;
using PlaNEvent.Api.Data;

namespace PlaNEvent.Api.Infrastructure;

public static class SchemaBootstrapper
{
    public static async Task ApplyAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        var sql = """
            CREATE TABLE IF NOT EXISTS "Categories" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OwnerId" text NOT NULL,
                "ParentCategoryId" integer NULL,
                "Name" text NOT NULL,
                "Color" text NOT NULL DEFAULT '#2f80ff',
                "IsActive" boolean NOT NULL DEFAULT TRUE
            );

            CREATE TABLE IF NOT EXISTS "Offerings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OwnerId" text NOT NULL,
                "CategoryId" integer NULL,
                "Name" text NOT NULL,
                "Description" text NOT NULL DEFAULT '',
                "Price" numeric(18,2) NOT NULL DEFAULT 25,
                "Color" text NOT NULL DEFAULT '#ec3e47',
                "CoverImageUrl" text NOT NULL DEFAULT '',
                "IsPublished" boolean NOT NULL DEFAULT FALSE,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                "AllowNewBookings" boolean NOT NULL DEFAULT TRUE,
                "LimitBookingPeriodDays" integer NULL,
                "RequireSignUpEveryTime" boolean NOT NULL DEFAULT FALSE
            );

            CREATE TABLE IF NOT EXISTS "OfferingRuleGroups" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OfferingId" integer NOT NULL,
                "Name" text NOT NULL,
                "Color" text NOT NULL DEFAULT '#ec3e47',
                "StartDateUtc" timestamp with time zone NOT NULL,
                "EndDateUtc" timestamp with time zone NULL,
                "FrequencyType" text NOT NULL DEFAULT 'daysOfWeek',
                "WeekdaysCsv" text NOT NULL DEFAULT '',
                "Interval" integer NOT NULL DEFAULT 1,
                "NthWeekOfMonth" integer NULL,
                "DayOfMonth" integer NULL
            );

            CREATE TABLE IF NOT EXISTS "OfferingTimeslots" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RuleGroupId" integer NOT NULL,
                "IsAllDay" boolean NOT NULL DEFAULT FALSE,
                "StartTime" interval NOT NULL,
                "EndTime" interval NOT NULL,
                "RepeatGeneratedSlots" boolean NOT NULL DEFAULT FALSE,
                "RepeatUntilLastStartTime" interval NULL,
                "RepeatEveryMinutes" integer NULL
            );

            CREATE TABLE IF NOT EXISTS "ShowcasePages" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OwnerId" text NOT NULL,
                "Name" text NOT NULL,
                "Slug" text NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                "IsHomePage" boolean NOT NULL DEFAULT FALSE
            );

            CREATE TABLE IF NOT EXISTS "ShowcasePageItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ShowcasePageId" integer NOT NULL,
                "Name" text NOT NULL,
                "SourceType" text NOT NULL DEFAULT 'category',
                "SourceId" integer NOT NULL,
                "CarouselType" text NOT NULL DEFAULT 'carousel',
                "Description" text NOT NULL DEFAULT '',
                "Blur" boolean NOT NULL DEFAULT FALSE,
                "HideTitle" boolean NOT NULL DEFAULT FALSE,
                "ShowDescription" boolean NOT NULL DEFAULT TRUE,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                "SortOrder" integer NOT NULL DEFAULT 0
            );

            ALTER TABLE "StaffMembers" ADD COLUMN IF NOT EXISTS "TrainingQualityRating" numeric(10,2) NOT NULL DEFAULT 0;
            ALTER TABLE "Offerings" ADD COLUMN IF NOT EXISTS "Price" numeric(18,2) NOT NULL DEFAULT 25;
            ALTER TABLE "Offerings" ALTER COLUMN "Price" SET DEFAULT 25;
            UPDATE "Offerings" SET "Price" = 25 WHERE COALESCE("Price", 0) <= 0;

            CREATE TABLE IF NOT EXISTS "StaffOfferingMappings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "StaffMemberId" integer NOT NULL,
                "OfferingId" integer NOT NULL,
                "ProficiencyLevel" text NOT NULL DEFAULT 'Intermediate'
            );

            CREATE TABLE IF NOT EXISTS "SageGoalSettings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OwnerId" text NOT NULL,
                "FacilityBusinessSummary" text NOT NULL DEFAULT '',
                "ExpectedMonthlyBookingCount" integer NOT NULL DEFAULT 0,
                "ExpectedMonthlySalesAmount" numeric(18,2) NOT NULL DEFAULT 0
            );

            CREATE TABLE IF NOT EXISTS "SageGoalFeatures" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SageGoalSettingsId" integer NOT NULL,
                "Name" text NOT NULL DEFAULT '',
                "ExpectedMonthlyBookingCount" integer NOT NULL DEFAULT 0,
                "ExpectedMonthlySalesAmount" numeric(18,2) NOT NULL DEFAULT 0,
                "TargetSharePercent" numeric(10,2) NOT NULL DEFAULT 0,
                "SortOrder" integer NOT NULL DEFAULT 0
            );

            ALTER TABLE "Occurrences" ADD COLUMN IF NOT EXISTS "OfferingId" integer NULL;
            ALTER TABLE "Occurrences" ADD COLUMN IF NOT EXISTS "RuleGroupId" integer NULL;
            ALTER TABLE "Occurrences" ADD COLUMN IF NOT EXISTS "Color" text NOT NULL DEFAULT '#2f80ff';

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_Categories_Categories_ParentCategoryId'
                ) THEN
                    ALTER TABLE "Categories"
                    ADD CONSTRAINT "FK_Categories_Categories_ParentCategoryId"
                    FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_Offerings_Categories_CategoryId'
                ) THEN
                    ALTER TABLE "Offerings"
                    ADD CONSTRAINT "FK_Offerings_Categories_CategoryId"
                    FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_OfferingRuleGroups_Offerings_OfferingId'
                ) THEN
                    ALTER TABLE "OfferingRuleGroups"
                    ADD CONSTRAINT "FK_OfferingRuleGroups_Offerings_OfferingId"
                    FOREIGN KEY ("OfferingId") REFERENCES "Offerings" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_OfferingTimeslots_OfferingRuleGroups_RuleGroupId'
                ) THEN
                    ALTER TABLE "OfferingTimeslots"
                    ADD CONSTRAINT "FK_OfferingTimeslots_OfferingRuleGroups_RuleGroupId"
                    FOREIGN KEY ("RuleGroupId") REFERENCES "OfferingRuleGroups" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_ShowcasePageItems_ShowcasePages_ShowcasePageId'
                ) THEN
                    ALTER TABLE "ShowcasePageItems"
                    ADD CONSTRAINT "FK_ShowcasePageItems_ShowcasePages_ShowcasePageId"
                    FOREIGN KEY ("ShowcasePageId") REFERENCES "ShowcasePages" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_StaffOfferingMappings_StaffMembers_StaffMemberId'
                ) THEN
                    ALTER TABLE "StaffOfferingMappings"
                    ADD CONSTRAINT "FK_StaffOfferingMappings_StaffMembers_StaffMemberId"
                    FOREIGN KEY ("StaffMemberId") REFERENCES "StaffMembers" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_StaffOfferingMappings_Offerings_OfferingId'
                ) THEN
                    ALTER TABLE "StaffOfferingMappings"
                    ADD CONSTRAINT "FK_StaffOfferingMappings_Offerings_OfferingId"
                    FOREIGN KEY ("OfferingId") REFERENCES "Offerings" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_SageGoalFeatures_SageGoalSettings_SageGoalSettingsId'
                ) THEN
                    ALTER TABLE "SageGoalFeatures"
                    ADD CONSTRAINT "FK_SageGoalFeatures_SageGoalSettings_SageGoalSettingsId"
                    FOREIGN KEY ("SageGoalSettingsId") REFERENCES "SageGoalSettings" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_Occurrences_Offerings_OfferingId'
                ) THEN
                    ALTER TABLE "Occurrences"
                    ADD CONSTRAINT "FK_Occurrences_Offerings_OfferingId"
                    FOREIGN KEY ("OfferingId") REFERENCES "Offerings" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_Occurrences_OfferingRuleGroups_RuleGroupId'
                ) THEN
                    ALTER TABLE "Occurrences"
                    ADD CONSTRAINT "FK_Occurrences_OfferingRuleGroups_RuleGroupId"
                    FOREIGN KEY ("RuleGroupId") REFERENCES "OfferingRuleGroups" ("Id") ON DELETE SET NULL;
                END IF;
            END $$;

            CREATE INDEX IF NOT EXISTS "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");
            CREATE INDEX IF NOT EXISTS "IX_Offerings_CategoryId" ON "Offerings" ("CategoryId");
            CREATE INDEX IF NOT EXISTS "IX_OfferingRuleGroups_OfferingId" ON "OfferingRuleGroups" ("OfferingId");
            CREATE INDEX IF NOT EXISTS "IX_OfferingTimeslots_RuleGroupId" ON "OfferingTimeslots" ("RuleGroupId");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowcasePages_OwnerId_Slug" ON "ShowcasePages" ("OwnerId", "Slug");
            CREATE INDEX IF NOT EXISTS "IX_ShowcasePageItems_ShowcasePageId" ON "ShowcasePageItems" ("ShowcasePageId");
            CREATE INDEX IF NOT EXISTS "IX_StaffOfferingMappings_StaffMemberId" ON "StaffOfferingMappings" ("StaffMemberId");
            CREATE INDEX IF NOT EXISTS "IX_StaffOfferingMappings_OfferingId" ON "StaffOfferingMappings" ("OfferingId");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SageGoalSettings_OwnerId" ON "SageGoalSettings" ("OwnerId");
            CREATE INDEX IF NOT EXISTS "IX_SageGoalFeatures_SageGoalSettingsId" ON "SageGoalFeatures" ("SageGoalSettingsId");
            CREATE INDEX IF NOT EXISTS "IX_Occurrences_OfferingId" ON "Occurrences" ("OfferingId");
            CREATE INDEX IF NOT EXISTS "IX_Occurrences_RuleGroupId" ON "Occurrences" ("RuleGroupId");
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }
}
